Repository epam/Indigo, pull requests merged in 2020-08, with the labels that each got.

#176 Add action to trigger gitlab tests with SRC_REV
  .github/workflows/gitlab_tests.yml
Labels: CI

#178 core: render2d: fix bug with invalid array size in _precalcScale
  render2d/src/render_internal.cpp
Labels: Indigo API, bug

#173 clean up Indigo Java API
  .appveyor.yml
  .travis.yml
  api/java/.gitignore
  api/java/.mvn/wrapper/MavenWrapperDownloader.java
  api/java/.mvn/wrapper/maven-wrapper.properties
  api/java/README.md
  api/java/mvnw
  api/java/mvnw.cmd
  api/java/pom.xml
  api/java/src/main/java/com/epam/indigo/Indigo.java
  api/java/src/main/java/com/epam/indigo/IndigoException.java
  api/java/src/main/java/com/epam/indigo/IndigoLib.java
  api/java/src/main/java/com/epam/indigo/IndigoObject.java
  api/java/src/test/java/com/epam/indigo/IndigoTests.java
  api/make-java-wrappers.py
  api/plugins/bingo/java/.gitignore
  api/plugins/bingo/java/.mvn/wrapper/MavenWrapperDownloader.java
  api/plugins/bingo/java/.mvn/wrapper/maven-wrapper.properties
  api/plugins/bingo/java/mvnw
  api/plugins/bingo/java/mvnw.cmd
  api/plugins/bingo/java/pom.xml
  api/plugins/bingo/java/src/main/java/com/epam/indigo/Bingo.java
  api/plugins/bingo/java/src/main/java/com/epam/indigo/BingoException.java
  api/plugins/bingo/java/src/main/java/com/epam/indigo/BingoLib.java
  api/plugins/bingo/java/src/main/java/com/epam/indigo/BingoObject.java
  api/plugins/bingo/java/src/test/java/com/epam/indigo/BingoTests.java
  api/plugins/inchi/java/.gitignore
  api/plugins/inchi/java/.mvn/wrapper/MavenWrapperDownloader.java
  api/plugins/inchi/java/.mvn/wrapper/maven-wrapper.properties
  api/plugins/inchi/java/mvnw
  api/plugins/inchi/java/mvnw.cmd
  api/plugins/inchi/java/pom.xml
  api/plugins/inchi/java/src/main/java/com/epam/indigo/IndigoInchi.java
  api/plugins/inchi/java/src/main/java/com/epam/indigo/IndigoInchiLib.java
  api/plugins/inchi/java/src/test/java/com/epam/indigo/IndigoInchiTests.java
  api/plugins/renderer/java/.gitignore
  api/plugins/renderer/java/.mvn/wrapper/MavenWrapperDownloader.java
  api/plugins/renderer/java/.mvn/wrapper/maven-wrapper.properties
  api/plugins/renderer/java/mvnw
  api/plugins/renderer/java/mvnw.cmd
  api/plugins/renderer/java/pom.xml
  api/plugins/renderer/java/src/main/java/com/epam/indigo/IndigoRenderer.java
  api/plugins/renderer/java/src/main/java/com/epam/indigo/IndigoRendererLib.java
  api/plugins/renderer/java/src/test/java/com/epam/indigo/IndigoRendererTests.java
  common/jna/jna.jar
Labels: Indigo API, enhancement
